version: 2
updates:
- package-ecosystem: cargo
  directory: '/'
  schedule:
    interval: monthly
  commit-message:
    prefix: ''
  allow:
  - dependency-type: all
  ignore:
  groups:
    cargo:
      patterns: ['*']

- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: monthly
  commit-message:
    prefix: ''
  groups:
    github-actions:
      patterns: ['*']
