name: Security audit

permissions:
  contents: read

on:
  pull_request:
    paths:
    - '**/Cargo.toml'
    - '**/Cargo.lock'
    - '.github/workflows/audit.yml'
  push:
    branches:
    - main
    - 'run-ci/**'
    - '**/run-ci/**'
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

jobs:
  security_audit:
    permissions:
      issues: write  # To create issues (actions-rs/audit-check).
      checks: write  # To create check (actions-rs/audit-check).
    runs-on: ubuntu-latest
    continue-on-error: true  # Prevent sudden announcement of a new advisory from failing CI.
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: taiki-e/install-action@83961fc0a2afe7f045535b5741d9a6418d7e1168 # v2.66.0
      with:
        tool: cargo-audit
    - name: Stub out `cargo generate-lockfile` to work around actions-rs/audit-check#163
      run: |
        cd ~/.cargo/bin
        mv cargo cargo.orig

        cat >cargo <<'EOF'
        #!/bin/sh
        set -eu
        # Assume the first argument is the subcommand, rather than an option. This is not robust,
        # but it works for the very simple call in actions-rs/audit-check, which is what matters.
        case "$1" in
        generate-lockfile)
          printf '::warning:: SKIPPING: %s %s\n' "$0" "$*" ;;
        *)
          exec "$0.orig" "$@" ;;
        esac
        EOF

        chmod +x cargo
    - uses: actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3 # v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  cargo_deny:
    permissions:
      issues: write  # To create issues (actions-rs/audit-check).
      checks: write  # To create check (actions-rs/audit-check).
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
        - bans licenses sources
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # v2.0.15
      with:
        command: check ${{ matrix.checks }}
        rust-version: stable
